name: brutal_ui
description: "Brutal UI is a Design System for Flutter, inspired by Brutalist Design."
publish_to: 'https://pub.dev'
version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
